version: '3'
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: server
        ports:
        - "3000:3000"
    keycloak:
        image: quay.io/keycloak/keycloak:23.0.4
        environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
        - "8080:8080"
        command:
        - start-dev
        container_name: keycloak

        
        