version: '3'
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile_server
        container_name: server
        ports:
        - "3000:3000"
    keycloak:
        image: quay.io/keycloak/keycloak:23.0.4
        environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
        - "8080:8080"
        command:
        - start-dev
        container_name: keycloak
    db:
        image: mysql:latest
        restart: always
        environment:
        MYSQL_ROOT_PASSWORD: isstmolamogollon
        MYSQL_DATABASE: nutriapp
        ports:
        - "4000:4000"
        volumes:
        - ./data:/var/lib/mysql

    api:
        build:
            context: .
            dockerfile: Dockerfile_py
        ports:
        - "5000:5000"
        depends_on:
        - db
            
        